### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by hughsaffar** [gocanto/google-autocomplete#33]
I am just wondering how to have multiple instances of the component?
Currently it could not render more than one and it does not throw any error!

**Comment by gocanto** [comment]
Do you have any code to see?.

You are able to assign id to the component using the last release

**Comment by hughsaffar** [comment]
I can see the both components by using different "input_id". But the problem is that they are not functioning. I see the following error in the console:
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

**Comment by gocanto** [comment]
I will give a try and let you know. I think this might be a easy fix

**Comment by olefirenko** [comment]
Hi! I also tried to use your component with multiple instances, but could not. So I ended up creating my component for Google Places Autocomplete https://github.com/olefirenko/vue-google-autocomplete.
The issue is that when you include multiple instances the component adding multiple `script` tags for calling `https://maps.googleapis.com/maps/api/js` and that is why it gives errors. So you need to include this script only one time and then all should work fine. I solved this issue by separating loading of Google maps API js from the component, so it is user responsibility to load this script first. Hope it can help you :-)

**Comment by andredaniel** [comment]
I am with the same problem too.

**Comment by gocanto** [comment]
Gave it a try today and found out that if google is included in header everything works just fine. But, I wanna do it from the JS so there is not need to include libs. 

Thoughts are welcome, so are PR's. 

Thanks a lot for testing
